sequenceDiagram
    participant Cliente
    participant Servidor

    Cliente->>Servidor: HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa
    Servidor-->>Cliente: spa HTML document
   
    Cliente->>Servidor: HTTP GET https://studies.cs.helsinki.fi/exampleapp/main.css
    Servidor-->>Cliente: CSS file

    Cliente->>Servidor: HTTP GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    Servidor-->>Cliente: spa JS file

    Cliente->>Servidor: HTTP GET https://studies.cs.helsinki.fi/exampleapp/data.json
    Servidor-->>Cliente: JSON data



